name: "Install dependencies"

description: "Installs pnpm globally"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pnpm
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm

    - name: Install project dependencies
      shell: bash
      run: pnpm install
